version: "3.8"
services:
  station-inventory:
    build:
      context: ./station-inventory
    command: ["java", "-jar", "/app/app.jar"]
    ports:
      - "9002:8080"
    env_file:
      - .env
    depends_on:
      - station-inventory-db
      - eureka-server
    networks:
      - evnet

  station-inventory-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=stationdb
      - POSTGRES_USER=ev
      - POSTGRES_PASSWORD=evpass
    ports:
      - "5434:5432"
    networks:
      - evnet

  eureka-server:
    image: eurekaserver:latest
    ports:
      - "8761:8761"
    networks:
      - evnet

networks:
  evnet:
    driver: bridge
