version: "3.8"
services:
  booking-swap:
    build:
      context: ./booking-swap
    command: ["java", "-jar", "/app/app.jar"]
    ports:
      - "9003:8080"
    env_file:
      - .env
    depends_on:
      - booking-swap-db
      - eureka-server
    networks:
      - evnet

  booking-swap-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=bookingdb
      - POSTGRES_USER=ev
      - POSTGRES_PASSWORD=evpass
    ports:
      - "5435:5432"
    networks:
      - evnet

  eureka-server:
    image: eurekaserver:latest
    ports:
      - "8761:8761"
    networks:
      - evnet

networks:
  evnet:
    driver: bridge
