version: "3.8"
services:
  geo-routing:
    build:
      context: ./geo-routing
    command: ["java", "-jar", "/app/app.jar"]
    ports:
      - "9009:8080"
    env_file:
      - .env
    depends_on:
      - eureka-server
    networks:
      - evnet

  eureka-server:
    image: eurekaserver:latest
    ports:
      - "8761:8761"
    networks:
      - evnet

networks:
  evnet:
    driver: bridge
