server:
  port: 8080

spring:
  application:
    name: geo-routing
  docker:
    compose:
      enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

geo-routing:
  api-key: ${MAPS_API_KEY:}
  cache:
    ttl: 3600000  # 1 giờ
    max-entries: 1000

logging:
  level:
    org.springframework: INFO
    com.boilerplate.code: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
