server:
  port: 8080

spring:
  application:
    name: notification

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

  mail:
    host: ${MAIL_HOST:mailhog}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka:9092}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

notification:
  sms:
    provider: ${SMS_PROVIDER:mock}
    api-key: ${SMS_API_KEY:}
  push:
    provider: ${PUSH_PROVIDER:mock}
    api-key: ${PUSH_API_KEY:}

docker:
  compose:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
