version: "3.8"
services:
  auth-user:
    build:
      context: ./auth-user
    command: ["java", "-jar", "/app/app.jar"]
    ports:
      - "9001:8080"
    env_file:
      - .env
    depends_on:
      - auth-user-db
      - eureka-server
    networks:
      - evnet

  auth-user-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=authdb
      - POSTGRES_USER=ev
      - POSTGRES_PASSWORD=evpass
    ports:
      - "5433:5432"
    networks:
      - evnet

  eureka-server:
    image: eurekaserver:latest
    ports:
      - "8761:8761"
    networks:
      - evnet

networks:
  evnet:
    driver: bridge
