version: "3.8"
services:
  admin:
    build:
      context: ./admin
    command: ["java", "-jar", "/app/app.jar"]
    ports:
      - "9005:8080"
    env_file:
      - .env
    depends_on:
      - admin-db
      - eureka-server
    networks:
      - evnet

  admin-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=admindb
      - POSTGRES_USER=ev
      - POSTGRES_PASSWORD=evpass
    ports:
      - "5437:5432"
    networks:
      - evnet

  eureka-server:
    image: eurekaserver:latest
    ports:
      - "8761:8761"
    networks:
      - evnet

networks:
  evnet:
    driver: bridge
