version: "3.8"
services:
  billing-payment:
    build:
      context: ./billing-payment
    command: ["java", "-jar", "/app/app.jar"]
    ports:
      - "9004:8080"
    env_file:
      - .env
    depends_on:
      - billing-payment-db
      - eureka-server
    networks:
      - evnet

  billing-payment-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=billingdb
      - POSTGRES_USER=ev
      - POSTGRES_PASSWORD=evpass
    ports:
      - "5436:5432"
    networks:
      - evnet

  eureka-server:
    image: eurekaserver:latest
    ports:
      - "8761:8761"
    networks:
      - evnet

networks:
  evnet:
    driver: bridge
