spring:
  application:
    name: billing-payment
  datasource:
    url: jdbc:postgresql://${BILLING_PAYMENT_DB_HOST:localhost}:${BILLING_PAYMENT_DB_PORT:5432}/${BILLING_PAYMENT_DB_NAME:billingdb}
    username: ${BILLING_PAYMENT_DB_USER:ev}
    password: ${BILLING_PAYMENT_DB_PASSWORD:evpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/billing-payment
    url: jdbc:postgresql://${BILLING_PAYMENT_DB_HOST:localhost}:${BILLING_PAYMENT_DB_PORT:5432}/${BILLING_PAYMENT_DB_NAME:billingdb}
    user: ${BILLING_PAYMENT_DB_USER:ev}
    password: ${BILLING_PAYMENT_DB_PASSWORD:evpass}
  docker:
    compose:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    com.boilerplate.code: DEBUG
    org.flywaydb: DEBUG
