spring:
  application:
    name: admin
  datasource:
    url: jdbc:postgresql://${ADMIN_DB_HOST:localhost}:${ADMIN_DB_PORT:5432}/${ADMIN_DB_NAME:admindb}
    username: ${ADMIN_DB_USER:ev}
    password: ${ADMIN_DB_PASSWORD:evpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

  docker:
    compose:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    com.boilerplate.code: DEBUG
